export enum CarouselActionsEnum {
  FETCH_CAROUSEL_PICTURES = 'FETCH_CAROUSEL_PICTURES',
  STORE_PICTURE_LIST = 'STORE_PICTURE_LIST',
  CHANGE_PICTURE_INPUT = 'CHANGE_PICTURE_INPUT',
  ADD_PICTURE = 'ADD_PICTURE',
  CAROUSEL_FAILURE = 'CAROUSEL_FAILURE',
  DISPLAY_REMOVE_BOX = 'DISPLAY_REMOVE_BOX',
  HIDE_REMOVE_BOX = 'HIDE_REMOVE_BOX',
  DELETE_PICTURE = 'DELETE_PICTURE',
  UPDATE_PICTURE = 'UPDATE_PICTURE',
  CHANGE_POSITION = 'CHANGE_POSITION',
}

export enum ConcertActionsEnum {
  FETCH_CONCERT_LIST = 'FETCH_CONCERT_LIST',
  STORE_CONCERT_LIST = 'STORE_CONCERT_LIST',
  DISPLAY_REMOVE_BOX = 'DISPLAY_REMOVE_BOX',
  HIDE_REMOVE_BOX = 'HIDE_REMOVE_BOX',
  CHANGE_CONCERT_INPUT = 'CHANGE_CONCERT_INPUT',
  POST_ADD_CONCERT_FORM = 'POST_ADD_CONCERT_FORM',
  POST_EDIT_CONCERT_FORM = 'POST_EDIT_CONCERT_FORM',
  CONCERT_FAILURE = 'CONCERT_FAILURE',
  FETCH_CONCERT_DETAILS = 'FETCH_CONCERT_DETAILS',
  STORE_CONCERT_DETAILS = 'STORE_CONCERT_DETAILS',
  DELETE_CONCERT = 'DELETE_CONCERT',
}

export enum GlobalActionsEnum {
  TOOGLE_LANGUAGE = 'TOOGLE_LANGUAGE',
  TOOGLE_HEADER_MENU = 'TOOGLE_HEADER_MENU',
  SET_TARGET_SECTION = 'SET_TARGET_SECTION',
}

export enum LoginActionsEnum {
  CHANGE_LOGIN_INPUT = 'CHANGE_LOGIN_INPUT',
  POST_LOGIN_FORM = 'POST_LOGIN_FORM',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
}

export enum NewsActionsEnum {
  FETCH_NEWS_LIST = 'FETCH_NEWS_LIST',
  STORE_NEWS_LIST = 'STORE_NEWS_LIST',
  DISPLAY_REMOVE_BOX = 'DISPLAY_REMOVE_BOX',
  HIDE_REMOVE_BOX = 'HIDE_REMOVE_BOX',
  CHANGE_NEWS_INPUT = 'CHANGE_NEWS_INPUT',
  POST_ADD_NEWS_FORM = 'POST_ADD_NEWS_FORM',
  POST_EDIT_NEWS_FORM = 'POST_EDIT_NEWS_FORM',
  NEWS_FAILURE = 'NEWS_FAILURE',
  FETCH_NEWS_DETAILS = 'FETCH_NEWS_DETAILS',
  STORE_NEWS_DETAILS = 'STORE_NEWS_DETAILS',
  DELETE_NEWS = 'DELETE_NEWS',
}
